### ISSUE TITLE
FAILED flash aop_a, dsp_a, qupfw_a and storsec_a (remote: 'Flashing is not allowed for Critical Partitions ')

### ISSUE THREAD

**Issue by mlkood** [Intrinsically-Sublime/fajita-factory-flash-bash-scripts#2]
Do you want to wipe all the data ( recommended )[Y/N]?y

** If wiping data fails but the install is successful ignore the error **
** If the install fails please boot into TWRP and use Wipe/Format first **

Erasing 'userdata'                                 OKAY [  0.589s]
/usr/bin/make_f2fs failed with status 1
fastboot: error: Cannot generate image for userdata
Do you want to flash the system 'a' partitions [Y/N]?y
Sending 'aop_a' (180 KB)                           OKAY [  0.013s]
Writing 'aop_a'                                    FAILED (remote: 'Flashing is not allowed for Critical Partitions
')
fastboot: error: Command failed
Invalid sparse file format at header magic
Sending sparse 'system_a' 1/4 (688428 KB)          OKAY [ 17.759s]
Writing 'system_a'                                 OKAY [  0.001s]
Sending sparse 'system_a' 2/4 (776905 KB)          OKAY [ 23.969s]
Writing 'system_a'                                 OKAY [  0.001s]
Sending sparse 'system_a' 3/4 (748790 KB)          OKAY [ 21.939s]
Writing 'system_a'                                 OKAY [  0.001s]
Sending sparse 'system_a' 4/4 (658046 KB)          OKAY [ 20.199s]
Writing 'system_a'                                 OKAY [  0.001s]
Finished. Total time: 85.939s
Sending 'vbmeta_a' (4 KB)                          OKAY [  0.010s]
Writing 'vbmeta_a'                                 OKAY [  0.001s]
Finished. Total time: 4.261s
Invalid sparse file format at header magic is not an error you need only to wait
Invalid sparse file format at header magic
Sending sparse 'vendor_a' 1/2 (785343 KB)          OKAY [ 20.295s]
Writing 'vendor_a'                                 OKAY [  0.001s]
Sending sparse 'vendor_a' 2/2 (31404 KB)           OKAY [  6.709s]
Writing 'vendor_a'                                 OKAY [  0.002s]
Finished. Total time: 27.760s
Sending 'LOGO_a' (3160 KB)                         OKAY [  0.090s]
Writing 'LOGO_a'                                   OKAY [  0.026s]
Finished. Total time: 14.315s
Do you want to flash the system 'b' partitions [Y/N]?y
Sending 'aop_b' (180 KB)                           OKAY [  0.007s]
Writing 'aop_b'                                    FAILED (remote: 'Flashing is not allowed for Critical Partitions
')
fastboot: error: Command failed
Invalid sparse file format at header magic
Sending sparse 'system_b' 1/4 (688428 KB)          OKAY [ 17.626s]
Writing 'system_b'                                 OKAY [  0.001s]
Sending sparse 'system_b' 2/4 (776905 KB)          OKAY [ 24.088s]
Writing 'system_b'                                 OKAY [  0.001s]
Sending sparse 'system_b' 3/4 (748790 KB)          OKAY [ 22.239s]
Writing 'system_b'                                 OKAY [  0.001s]
Sending sparse 'system_b' 4/4 (658046 KB)          OKAY [ 19.899s]
Writing 'system_b'                                 OKAY [  0.001s]
Finished. Total time: 84.310s
Sending 'vbmeta_b' (4 KB)                          OKAY [  0.004s]
Writing 'vbmeta_b'                                 OKAY [  0.001s]
Finished. Total time: 4.101s
Invalid sparse file format at header magic is not an error you need only to wait
Invalid sparse file format at header magic
Sending sparse 'vendor_b' 1/2 (785343 KB)          OKAY [ 20.286s]
Writing 'vendor_b'                                 OKAY [  0.001s]
Sending sparse 'vendor_b' 2/2 (31404 KB)           OKAY [  6.899s]
Writing 'vendor_b'                                 OKAY [  0.001s]
Finished. Total time: 27.379s
Sending 'LOGO_b' (3160 KB)                         OKAY [  0.084s]
Writing 'LOGO_b'                                   OKAY [  0.014s]
Finished. Total time: 14.404s
Do you want to flash 'persist' [Y/N]?y
Sending 'persist' (32768 KB)                       OKAY [  0.858s]
Writing 'persist'                                  FAILED (remote: 'Flashing is not allowed for Critical Partitions
')
fastboot: error: Command failed
Do you want to flash the recovery 'a' partitions [Y/N]?y
Starting TWRP on the phone

Sending 'boot.img' (31136 KB)                      OKAY [  0.798s]
Booting                                            OKAY [  0.079s]
Finished. Total time: 0.913s

**Comment by Intrinsically-Sublime** [comment]
I think the ```fastboot: error: Command failed``` error is a result of having an encrypted partition.

You can try ```fastboot flashing unlock_critical```

or you may need to format it using TWRP. 

But only if the install fails and will not boot. Some partitions may not need to be re-flashed and the errors can be ignored.

The ```fastboot: error: Command failed``` could be from a bad USB connection. If you are using a USB 3 port try using a USB 2 dock between the phone and the computer.
