### ISSUE TITLE
Addition to readme

### ISSUE THREAD

**Issue by ethical2012** [Intrinsically-Sublime/fajita-factory-flash-bash-scripts#3]
The phone's bootloader needs to be in a locked state after the flash to be able to boot otherwise it will get stuck on the loading screen.  This took me far too longer than it should have to figure out why OOS was not loading. LOL

after install
`fastboot oem lock`

may want to add the option to unlock it later if possible

ABSOLUTELY GREAT WORK THIS IS SAVING ME TONS OF TIME THANK YOU!

**Comment by Intrinsically-Sublime** [comment]
That is strange. I created the script to use before installing Ubuntu Touch and you must leave it unlocked to install Ubuntu Touch. I have used it many times and booted to OOS every time after flashing and before installing Ubuntu Touch.

I wonder if your phone was encrypted or there was something else unusual about it that forced you to lock it again. Either way I am glad it was useful to you.

**Comment by ethical2012** [comment]
I believe it was encrypted actually.  I guess I had thought that was only the data partition and not the kernel though I could be completely wrong.  I also wonder if it had something to do with unlocking via fastboot or within OOS itself.  Possibly I had something on the lines of one was enabled and the other was not.  Or, possibly the downgrade to 9,  I believe I was on 11.  Not sure right now, if I get some time here soon I will try and reproduce the issue.
