### ISSUE TITLE
How to adapt to OnePlus 6?

### ISSUE THREAD

**Issue by iconoclasthero** [Intrinsically-Sublime/fajita-factory-flash-bash-scripts#4]
In your OP there are the following two questions which are essentially the same as mine:  How do I adapt this for the 6?  I looked at a couple of the scripts and assuming that I have the correct images, it looks like it should be fairly straight forward, especially if the 6 and 6T shipped with the same major version of the OS?

[hekathegreat](https://forums.ubports.com/user/hekathegreat)
[18 Feb 2022, 15:05](https://forums.ubports.com/post/62036)

Hi, is this possible to make work with oneplus6 (without the "T")?

I have also messing around with different os's and everytime I flash something evolved with linux, I cant go back to stock android with my oneplus6. It would be great to have some sort of backup to work with.

 0 
11 days later
[ronbillock](https://forums.ubports.com/user/ronbillock)
ronbillock
[1 Mar 2022, 20:46](https://forums.ubports.com/post/62474)

[@antidroid](https://forums.ubports.com/uid/6533) 1) Will this also work on an OP6? 2) I am not sure of the process. Where do I run the flash_all.sh, from my laptop terminal or from the phone? Do I need to download the files to my Linux laptop or will they be pulled in when the script is executed? Sorry I am pretty non-technical and new to all this but want to get my OP6 back to factory so i can try to install LineageOS.

**Comment by Intrinsically-Sublime** [comment]
To be honest I do not know if the img files I have included are the correct ones for an op6. To be sure you could find the op6 files and replace them.

To run them you download and extract all the files to a folder and then open that location in a terminal window and execute the scripts. Be sure you have the android tools installed already.

If you have a Windows computer available it is much easier with the MSM download tool. https://xdaforums.com/t/op6-latest-10-3-8-collection-of-unbrick-tools.3914109/ it can restore the phone even when it is frozen and can not be connected to with android tools.
